version: '3.2'
services:
  app:
    image: "kokouu/nodejs-dev:v5"
    container_name: app
    working_dir: /usr/workspace
    volumes:
      - type: bind
        source: ./workspace
        target: /usr/workspace
      - type: volume
        source: f-node_modules
        target: /usr/workspace/mean-course/node_modules
    tty: true
    depends_on:
      - db
  db:
    image: mongo:5.0.9-focal
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: FEr1htR48pELN6
    volumes:
      - type: volume
        source: db-data
        target: /data/db
        volume:
          nocopy: true
  ui:
    image: mongo-express:0.54
    container_name: ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: FEr1htR48pELN6
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db
volumes:
  db-data:
  f-node_modules:
  b-node_modules: